name: Execute Tests

on:
  workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_publish_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Inatall Dependecncy
        run: npm ci
      - name: Inatall Allure globally
        run: npm i -g allure-commandline
      - name: Run Tests
        if: always()
        run: npm run wdio:action
        continue-on-error: true
      - name: Generate Allure Report
        if: always()
        run: npm run report
        continue-on-error: true
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        if: always()
        continue-on-error: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=allure-report --prod
      - name: Archive Test results
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
